#!/bin/bash
lv_command="$1"
attribute="$2"
project_path="/home/nour/Documents/projects/Laravel/"
script_path="$(realpath "$0")"
script_dir="$(dirname "$(realpath "$0")")"
entry=$(grep "^$attribute |" "$script_dir/laravel.log")
pid=$(echo "$entry" | awk -F'|' '{print $2}' | xargs)
port=$(echo "$entry" | awk -F'|' '{print $3}' | xargs)
if [ "$lv_command" = "start" ]; then
	    if [ -n "$attribute" ]; then
		    if [ "$(systemctl is-active mysqld.service)" = 'inactive' ]; then
			    echo 'Starting mysql server...'
			    sudo systemctl start mysqld.service
		    fi

		    if [ -n "$entry" ]; then
			echo "your project is already served on http://localhost:$port"
			exit 0
		    fi
		            echo "Starting Laravel server for project: $attribute"
			            nohup php "$project_path$attribute/artisan" serve > "$script_dir/out.log" 2>&1 & 
				    server_pid=$!
				    disown
				    url=$(tail -n +1 -F "$script_dir/out.log" | grep -m1 -oE 'http://127.0.0.1:[0-9][0-9][0-9][0-9]')
				    server_port=$(echo $url | grep -oE '[0-9][0-9][0-9][0-9]')
				    echo "$attribute | $server_pid | $server_port" >> "$script_dir/laravel.log"
				    if [ -n "$url" ]; then
					       xdg-open "$url"
						echo "your project served on $url"
					else
						    echo "No URL found in $script_dir/out.log"  
				    fi
		else
		echo "Error: No project specified."
		fi

elif [ "$lv_command" = "stat" ]; then
	 netstat -tulnp 2>$script_dir/warning.log| grep -o 127.0.0.1:80*
elif [ "$lv_command" = "list" ]; then
	if [ -s "$script_dir/laravel.log" ]; then
	echo "Running Laravel projects:"
	awk -F'|' '{
		    port=$3
		        gsub(/^ +| +$/, "", port)     # trim leading/trailing spaces
			    print "Project: " $1 ", PID: " $2 ", URL: http://localhost:" port
		    }' "$script_dir/laravel.log"
   	else
		echo "There's no running projects";
	fi
elif [ "$lv_command" = "kill" ] || [ "$lv_command" = "stop" ]; then
	if [ -n "$pid" ]; then 
		echo "Stopping $attribute ..."
		kill $pid
		> "$script_dir/laravel.log"
	elif [ "$attribute" = "all" ]; then
		echo "Stopping all Laravel servers..."
		while IFS='|' read -r project pid url; do
		pid=$(echo "$pid" | xargs)
		if kill -0 "$pid" 2>/dev/null; then
		echo "Stopping $project (PID $pid)"
		kill "$pid"
		fi
		done < "$script_dir/laravel.log"
		# Clear the log
		> "$script_dir/laravel.log"
fi
else
	 echo "This is not a valid Laravel command. Use 'start' or 'stat' or 'kill' or 'list'"
fi

